create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade);
create table if not exists public.posts(id bigint generated by default as identity primary key,title text not null,category text default 'Updates',content text,image_url text,published boolean default true,author_id uuid references auth.users(id),created_at timestamptz default now());
alter table public.admin_users enable row level security; alter table public.posts enable row level security;
create policy "Public read published" on public.posts for select to anon,authenticated using(published=true);
create policy "Admin insert" on public.posts for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=auth.uid()));
create policy "Admin update" on public.posts for update to authenticated using(exists(select 1 from public.admin_users where user_id=auth.uid())) with check(exists(select 1 from public.admin_users where user_id=auth.uid()));
create policy "Admin delete" on public.posts for delete to authenticated using(exists(select 1 from public.admin_users where user_id=auth.uid()));
create policy "Admin own row" on public.admin_users for select to authenticated using(user_id=auth.uid());
-- Create a PUBLIC Storage bucket named dds-media in the Supabase dashboard.
create policy "Admin media upload" on storage.objects for insert to authenticated with check(bucket_id='dds-media' and exists(select 1 from public.admin_users where user_id=auth.uid()));
create policy "Admin media update" on storage.objects for update to authenticated using(bucket_id='dds-media' and exists(select 1 from public.admin_users where user_id=auth.uid())) with check(bucket_id='dds-media' and exists(select 1 from public.admin_users where user_id=auth.uid()));
create policy "Admin media delete" on storage.objects for delete to authenticated using(bucket_id='dds-media' and exists(select 1 from public.admin_users where user_id=auth.uid()));